import sys
from random import choice

opts = [opt for opt in sys.argv[1:] if opt.startswith("-")]
args = [arg for arg in sys.argv[1:] if not arg.startswith("-")]

def main():
    topOfBubble = ("  ")
    bottomOfBubble = ("  ")
    counter = 0
    
    if len(sys.argv) < 2 or "-h" in opts:
        print("Usage: soysay [input] (must be in quotation marks) (args)")
        print("Options:")
        print(" --h, --help     Prints out this help message (also shown when no input is provided")
        print(" --random        Picks a random soyjak to display")
        print()
        print(" --soyjak        Uses the standard default soyjak")
        print(" --snoojak       Uses the Snoojak")
        print(" --gapejak       Uses the Gapejak")
        print(" --cobson        Uses the Cobson soyjak")
        print(" --markiplier    Uses the Markiplier soyjak")
        return
    userInput = sys.argv[1]
    while counter < len(userInput) + 2:
        topOfBubble = topOfBubble + "_"
        bottomOfBubble = bottomOfBubble + "-"
        counter = counter + 1
    print(topOfBubble)
    print(" <", userInput, ">")
    print(bottomOfBubble)
    
    def Soyjak():
        print("     \\                                      ")
        print("      \\     ...-############-...            ")
        print("       \\   -++--.            .--++-         ")
        print("       ..+-          ...         -+...      ")
        print("     -+-.           .-.          .--+-      ")
        print("    ++             ......            -#.    ")
        print("    ++             .-----.-.         .-+.   ")
        print("    ++                                .#.   ")
        print("   -+-         .---------    .--------  #-  ")
        print("   #-         -+.........    ........-+.#-  ")
        print("   #-                      ..            ++ ")
        print("   #-           .+##########+            .-#")
        print("   #--+   .++++++#- .#####.++----+#####+##+ ")
        print("   #--+         .#- .#####.++....-#####.#-+ ")
        print("   #-.          .#-        ++    -####+.+-+ ")
        print("    ++          .##++++++++#+  +--#++++++#+ ")
        print("    ++.   ..#-                  -+..    +-  ")
        print("     .-+. .-+.                   -#.        ")
        print("      .#.  .#-.         -#. ...  -#.    ##+ ")
        print("      .#.    ++             .--.         #- ")
        print("      .#.  .##+          .#-|||##+     #-   ")
        print("      .#.    -++-.      -#+#####++#. .-+.   ")
        print("      .#.      ..#-     -##########. -#.    ")
        print("      .#.     --.#-     -########+  .--.    ")
        print("     -+..       .#-     ..######+..+-.      ")
        print("    .-+   -#.     -####+--+##+-. .-+.       ")
        print("   #-.   -+..      ...#+.-+######+..        ")
    def Cobson():
        print("    /                                       ")
        print("   /    .                                   ")
        print("  /   .                          #          ")
        print("    .                             .         ")
        print("                                            ")
        print("   .                                        ")
        print("                                    #       ")
        print("                         #####              ")
        print("              #       .######### ----#      ")
        print("  #               ###### -- .- ##           ")
        print("  +#########-     #-     #-.#   #     -     ")
        print("  ##  # --             +##             +    ")
        print("###   ##.+ ##      #                        ")
        print("  -   #-            #  -#-              -   ")
        print(" .   -##--#                                 ")
        print("  #                                         ")
        print("  -       +              .               #  ")
        print("          -       ####    #              #  ")
        print("           ##+    ##.      +             ## ")
        print("            #                            ## ")
        print("  #-                                     -# ")
        print("  ##      #                              +##")
        print("  .-#         +         -                -# ")
        print("    #-         #  +                      # #")
        print("   ###       #. +     #####-            ##  ")
        print("    ##       ################     +    ##-  ")
        print("     ##      ##################        ##-- ")
        print(" #   -##      #################    #   ##   ")
        print("      -##      ###############         #-   ")
        print("      ###      ###############       ##--   ")
        print("       ###      ##-########          -#     ")
        print("         #.      # ###### ##        -##     ")
        print("         ###      .#  + .#    #-    #       ")
        print("           .#  ##           ###    #.       ")
        print("            +#+ + # -#-# # +       #+       ")
        print("             #-       +         ## #        ")
        print("              ###+             ###          ")  
    def Snoojak():
        print("     \\                                     ")
        print("      \\                *@*-      +@@@@+    ")
        print("       \\               @@ -@@@@@@@    @|   ")
        print("        \\             @@        @@    @|   ")
        print("         \\           =@*         +@@@@+    ")
        print("          \\          @@                    ")
        print("                   *@%@%+                   ")
        print("           -@@@@@@+:....:+@@@@@@            ")
        print(" +@@@@@@@@@+                    #@@%@@@@@@+ ")
        print("@@...:@@.                          -@@    @@")
        print("@@  @@        .:.           ..       .@@  @@")
        print("*@-@@       :*@@@*        *@@@*:       @@-@*")
        print("  @@        +*==**        **==*+        @@  ")
        print("  @@                                    @#  ")
        print("  @@ -        #     %@@=      +        :@-  ")
        print("   @@:=+     . =   + =  * +:-@ -= =-.  @%   ")
        print("    %@+.-*    *@@@@@@@@@@@@@@#.   = +%@@    ")
        print("      @@@#:.-  @@@@@@@@@@@@@+ : .:=@@%      ")
        print("        =@@@ :.=@@@@@@@@@@@.  .:#@@:        ")
        print("            @#  :@@@@@@@@@@   =@#           ")
        print("             %%-. @@- #.+@ . :@=+           ")
        print("               @-*   =%*   .@:*             ")
        print("               *%@= .:+*:+@+-               ")
        print("                  - *#+*+*                  ")
    def Markiplier():
        print("    \\                                      ")
        print("     \\        #################            ")
        print("      \\     #+                 +#          ")
        print("          ###                     ###       ")
        print("         #                           #      ")
        print("       ##                             #     ")
        print("      #           ##   ##              #    ")
        print("     #      #                          #    ")
        print("     #     #.    #          -#  ##     #    ")
        print("     #            #        -           +    ")
        print("     ####  ##########      .####   #######  ")
        print("    ###     #   #+  #    #     ###     ###  ")
        print("     #    -#  ###  ##    #+#  ##  #    ##   ")
        print("     ##             #     #            #+   ")
        print("     ### ###########      +#####       #    ")
        print("     #                                 #    ")
        print("     #            #         #          #    ")
        print("     #                        #        #    ")
        print("    -           # ++       ###          -   ")
        print("     #                                   ###")
        print("    #          #  ######+     #          #  ")
        print("   #+        #  .##  #  # # ##    #     ### ")
        print("    +      +   #  #  #  # # # #   #     .## ")
        print("    ## #   -  ##################  . # .+# # ")
        print("    ### +  #  ##################    # + #   ")
        print("     #.-+#-   ##################   #   #    ")
        print("     ## # #   ##################    ## ##   ")
        print("   ### #####  ##################  #   #.#   ")
        print("#      .-  #  ##################  . ###- ## ")
        print("     - ##  +  ##################   ##-   #  ")
        print("      ## -  .  ################  +  ## #+#  ")
        print("       #+.# .   ##############   #.# # +#   ")
        print("          ##.     ###########    +#  +#     ")
        print("          ###      #######+      +     .    ")
        print("           ######        .     .+##         ")
        print("            ## #-   # # #    #####          ")
        print("              ####   # +  ### ###           ")
        print("                 .## ###..+ ###             ")
    def Gapejak():
        print("     \\                                     ")
        print("      \\    +################+              ")
        print("       \\  +                  #             ")
        print("         .                       #          ")
        print("        #           #     -#                ")
        print("       .    .     .                         ")
        print("       -             #.   .###       #      ")
        print("   .###     #   -#             ##     #     ")
        print(" #   +        #  #     ####   .  ##    #    ")
        print("##       ###     ##  #  ###+- #    #        ")
        print(" #  #           +# +#####+           +  +   ")
        print("  # #    #     ##   #                 #     ")
        print("   #    # ###   ##  -                  +    ")
        print("  #       ..      #                      +  ")
        print("                                          # ")
        print(" #         .####-                         # ")
        print("         # # # # #  #                     # ")
        print("#         ##########  -                   # ")
        print("#         #############-  .         #     # ")
        print("         ###############   #       .+-   #  ")
        print(" .-      ###############           # .#- ## ")
        print("  #      ################   .         ##-+. ")
        print(" .#      ################    +     # ####   ")
        print("  ##   .  ###############            # ##-  ")
        print("  ###     ###############   #        - #### ")
        print("   ##.     #############             ###.   ")
        print("    +#     -##########-#           # ####   ")
        print("    ##      # ######.##       #   ## ##     ")
        print("    + #-      #.#  ##-      .###  #+#- +    ")
        print("     ###  ##              ####   ####     # ")
        print("   + ####+ # #           # -- ####-+## -    ")
        print("#    .# ##   ##        # ##  ####    #      ")
        print("         .###.## -######## # ###-           ")
        print("        #####      #--   # -# +             ")
        print("           .-##+     +# ### #.#             ")
        print("              ##+###++####    #             ")
        print("              . ##   # #                    ")

    if "--random" in opts:
        random = choice(["soy", "cob", "snoo", "mark", "gape"])
        if random == "soy":
            Soyjak()
            exit()
        if random == "cob":
            Cobson()
            exit()
        if random == "snoo":
            Snoojak()
            exit()
        if random == "mark":
            Markiplier()
            exit()
        if random == "gape":
            Gapejak()
            exit()
    if "--cobson" in opts:
        Cobson()
    if "--gapejak" in opts:
        Gapejak()
    elif "--snoojak" in opts:
        Snoojak()
    elif "--markiplier" in opts:
        Markiplier()
    else: Soyjak()

if __name__ == "__main__":
    main()
    
